services:
  webApp:
    container_name: webApp
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: blog-app:prod.v.0.0.1
    ports:
      - "80:3004"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    # keep a local Postgres in prod stack —
    #   swap to remote Supabase by deleting this block
    image: postgres:latest
    restart: always
    secrets:
      - db-password # mount secret rather than env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: blog-sample-project
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


secrets:
  db-password:
    file: dockers-creds/db-password.txt # same secret file you already created
