services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3003:3003
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/blog-sample-project
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db:
        condition: service_healthy
    develop:
      watch:
        - path: .
          target: /app
          action: sync
        - path: ./package.json
          action: reload
        - path: ./dev.Dockerfile
          action: reload
        - path: ./package-lock.json
          action: reload

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    secrets:
      - db-password

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: blog-sample-project
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    expose: [ "5432" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  db-password:
    file: dockers-creds/db-password.txt

volumes:
  db-data:
